// <auto-generated />
using System;
using CompraProgamada.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CompraProgamada.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260313204740_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("CompraProgamada.Domain.Entities.CestaRecomendacao", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("ID_CESTA_RECOMENDACAO");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("Ativa")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("ATIVO");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("DATA_CRIACAO");

                    b.Property<DateTime?>("DataDesativacao")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("DATA_DESATIVACAO");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("VARCHAR(100)")
                        .HasColumnName("NOME");

                    b.HasKey("Id");

                    b.ToTable("TB_CESTA_RECOMENDACAO", (string)null);
                });

            modelBuilder.Entity("CompraProgamada.Domain.Entities.Cliente", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("ID_CLIENTE");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true)
                        .HasColumnName("ATIVO");

                    b.Property<string>("CPF")
                        .IsRequired()
                        .HasColumnType("VARCHAR(11)")
                        .HasColumnName("CPF");

                    b.Property<DateTime>("DataAdesao")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("DATA_ADESAO");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("VARCHAR(200)")
                        .HasColumnName("EMAIL");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("VARCHAR(200)")
                        .HasColumnName("NOME");

                    b.Property<decimal>("ValorMensal")
                        .HasColumnType("DECIMAL(18,2)")
                        .HasColumnName("VALOR_MENSAL");

                    b.HasKey("Id");

                    b.HasIndex("CPF")
                        .IsUnique();

                    b.ToTable("TB_CLIENTES", (string)null);
                });

            modelBuilder.Entity("CompraProgamada.Domain.Entities.ContaGrafica", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("ID_CONTA_GRAFICA");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("ClienteId")
                        .HasColumnType("bigint")
                        .HasColumnName("CLIENTE_ID");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("DATA_CRIACAO");

                    b.Property<string>("NumeroConta")
                        .IsRequired()
                        .HasColumnType("VARCHAR(20)")
                        .HasColumnName("NUMERO_CONTA");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("TIPO");

                    b.HasKey("Id");

                    b.HasIndex("NumeroConta")
                        .IsUnique();

                    b.ToTable("TB_CONTAS_GRAFICAS", (string)null);
                });

            modelBuilder.Entity("CompraProgamada.Domain.Entities.ContaMaster", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("ID_CONTA_MASTER");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("DataAtualizacao")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("DATA_ATUALIZACAO");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("DATA_CRIACAO");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("VARCHAR(500)")
                        .HasColumnName("DESCRICAO");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("VARCHAR(100)")
                        .HasColumnName("NOME");

                    b.Property<decimal>("Preco")
                        .HasColumnType("DECIMAL(18,2)")
                        .HasColumnName("PRECO");

                    b.Property<int>("Quantidade")
                        .HasColumnType("int")
                        .HasColumnName("QUANTIDADE");

                    b.HasKey("Id");

                    b.ToTable("TB_CONTAS_MASTER", (string)null);
                });

            modelBuilder.Entity("CompraProgamada.Domain.Entities.Cotacao", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("ID_COTACAO");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("DataPregao")
                        .HasColumnType("DATE")
                        .HasColumnName("DATA_PREGAO");

                    b.Property<decimal>("PrecoAbertura")
                        .HasColumnType("DECIMAL(18,4)")
                        .HasColumnName("PRECO_ABERTURA");

                    b.Property<decimal>("PrecoFechamento")
                        .HasColumnType("DECIMAL(18,4)")
                        .HasColumnName("PRECO_FECHAMENTO");

                    b.Property<decimal>("PrecoMaximo")
                        .HasColumnType("DECIMAL(18,4)")
                        .HasColumnName("PRECO_MAXIMO");

                    b.Property<decimal>("PrecoMinimo")
                        .HasColumnType("DECIMAL(18,4)")
                        .HasColumnName("PRECO_MINIMO");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasColumnType("VARCHAR(10)")
                        .HasColumnName("TICKER");

                    b.HasKey("Id");

                    b.ToTable("TB_COTACOES", (string)null);
                });

            modelBuilder.Entity("CompraProgamada.Domain.Entities.Custodia", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("ID_CUSTODIA");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("ContaGraficaId")
                        .HasColumnType("bigint")
                        .HasColumnName("CONTA_GRAFICA_ID");

                    b.Property<DateTime>("DataUltimaAtualizacao")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("DATA_ULTIMA_ATUALIZACAO");

                    b.Property<decimal>("PrecoMedio")
                        .HasColumnType("DECIMAL(18,4)")
                        .HasColumnName("PRECO_MEDIO");

                    b.Property<int>("Quantidade")
                        .HasColumnType("int")
                        .HasColumnName("QUANTIDADE");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasColumnType("VARCHAR(10)")
                        .HasColumnName("TICKER");

                    b.HasKey("Id");

                    b.ToTable("TB_CUSTODIAS", (string)null);
                });

            modelBuilder.Entity("CompraProgamada.Domain.Entities.Distribuicao", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("ID_DISTRIBUICAO");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("CustodiaFilhoteId")
                        .HasColumnType("bigint")
                        .HasColumnName("CUSTODIA_FILHOTE_ID");

                    b.Property<DateTime>("DataDistribuicao")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("DATA_DISTRIBUICAO");

                    b.Property<long>("OrdemCompraId")
                        .HasColumnType("bigint")
                        .HasColumnName("ORDEM_COMPRA_ID");

                    b.Property<decimal>("PrecoUnitario")
                        .HasColumnType("DECIMAL(18,4)")
                        .HasColumnName("PRECO_UNITARIO");

                    b.Property<int>("Quantidade")
                        .HasColumnType("int")
                        .HasColumnName("QUANTIDADE");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasColumnType("VARCHAR(10)")
                        .HasColumnName("TICKER");

                    b.HasKey("Id");

                    b.ToTable("TB_DISTRIBUICOES", (string)null);
                });

            modelBuilder.Entity("CompraProgamada.Domain.Entities.EventosIR", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("ID_EVENTO_IR");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("ClienteId")
                        .HasColumnType("bigint")
                        .HasColumnName("CLIENTE_ID");

                    b.Property<DateTime>("DataEvento")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("DATA_EVENTO");

                    b.Property<bool>("PublicadoKafka")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("PUBLICADO_KAFKA");

                    b.Property<string>("TipoImposto")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("TIPO");

                    b.Property<decimal>("ValorBase")
                        .HasColumnType("DECIMAL(18,2)")
                        .HasColumnName("VALOR_BASE");

                    b.Property<decimal>("ValorImposto")
                        .HasColumnType("DECIMAL(18,2)")
                        .HasColumnName("VALOR_IR");

                    b.HasKey("Id");

                    b.ToTable("TB_EVENTOS_IR", (string)null);
                });

            modelBuilder.Entity("CompraProgamada.Domain.Entities.ItemCesta", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("ID_ITEM_CESTA");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("CestaRecomendacaoId")
                        .HasColumnType("bigint")
                        .HasColumnName("CESTA_ID");

                    b.Property<decimal>("Percentual")
                        .HasColumnType("DECIMAL(5,2)")
                        .HasColumnName("PERCENTUAL");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasColumnType("VARCHAR(10)")
                        .HasColumnName("TICKER");

                    b.HasKey("Id");

                    b.ToTable("TB_ITENS_CESTA", (string)null);
                });

            modelBuilder.Entity("CompraProgamada.Domain.Entities.OrdemCompra", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("ID_ORDEM_COMPRA");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("ContaMasterId")
                        .HasColumnType("bigint")
                        .HasColumnName("CONTA_MASTER_ID");

                    b.Property<DateTime>("DataExecucao")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("DATA_EXECUCAO");

                    b.Property<decimal>("PrecoUnitario")
                        .HasColumnType("DECIMAL(18,4)")
                        .HasColumnName("PRECO_UNITARIO");

                    b.Property<int>("Quantidade")
                        .HasColumnType("int")
                        .HasColumnName("QUANTIDADE");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasColumnType("VARCHAR(10)")
                        .HasColumnName("TICKER");

                    b.Property<string>("TipoMercado")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("TIPO_MERCADO");

                    b.HasKey("Id");

                    b.ToTable("TB_ORDENS_COMPRA", (string)null);
                });

            modelBuilder.Entity("CompraProgamada.Domain.Entities.Rebalanceamento", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("ID_REBALANCEAMENTO");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("ClienteId")
                        .HasColumnType("bigint")
                        .HasColumnName("CLIENTE_ID");

                    b.Property<DateTime>("DataRebalanceamento")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("DATA_REBALANCEAMENTO");

                    b.Property<int>("Quantidade")
                        .HasColumnType("int");

                    b.Property<string>("TickerComprado")
                        .IsRequired()
                        .HasColumnType("VARCHAR(10)")
                        .HasColumnName("TICKER_COMPRADO");

                    b.Property<string>("TickerVendido")
                        .IsRequired()
                        .HasColumnType("VARCHAR(10)")
                        .HasColumnName("TICKER_VENDIDO");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("TIPO");

                    b.Property<decimal>("ValorVenda")
                        .HasColumnType("DECIMAL(18,2)")
                        .HasColumnName("VALOR_VENDA");

                    b.HasKey("Id");

                    b.ToTable("TB_REBALANCEAMENTOS", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
